accounts/urls.py
from django.conf.urls import url

from .views import my_profile
from .views import copy_from_cart

app_name = 'accounts'

urlpatterns = [
	url(r'^profile/$', my_profile, name='my_profile'),
	url(r'^item/copy/(?P<item_id>[-\w]+)/$', copy_from_cart, name='copy_item'),


]

cart/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from .views import redirect_view


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profiles/', include('accounts.urls', namespace='accounts')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^cart/', include('shopping_cart.urls', namespace='shopping_cart')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'', redirect_view)
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url

from .views import product_list
from .views import search
from .views import downfile

app_name = 'products'

urlpatterns = [
    url(r'^$', product_list, name='product-list'),
    url(r'^search/$', search, name='search'),
    url(r'^downfile/$', downfile, name='downfile'),
]

shopping_cart/urls.py
from django.conf.urls import url


from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    success,
    balance
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^update-transaction/(?P<token>[-\w]+)/$', update_transaction_records,
        name='update_records'),
    url(r'^check_balance/$', balance, name='balance')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cart</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static '/images/new.png'%}" type="image/png">
    {% block head %}

    {% endblock head %}
    {% block style %}{% endblock style %}
    <style>
        .accordion_button{
            display:block;
            width:100%;
            border:none;
            padding:15px;
            outline:none;
            cursor:pointer;
            background:#5C5FAB;
            color:#ffffff;
            text-align:left;
            transition:background 0.2s;
            border-radius:7px;
        }

        .accordion_button::after{
            content:'\25be';
            float:right;
            transform:scale(1.5);
        }
        .accordion_button--active + .accordion_content {
            display:block;
        }

        .accordion_button--active {
            background:#5C5FAB;
        }

        .accordion_button--active::after{
            content:'\25b4';
        }

        .accordion_content{
            /*overflow:hidden;
            max-height:0;
            transition:max-height 0.2s;
            */
            padding: 28px 15px;
            font-family:sans-serif;
            background:#FFFFFF;


            display:none;
            overflow:auto;

        }

        .oval {
            width:120px;
        }

        .accordion_content >p {
            white-space: pre-line;
        }


        .rec_row {
            padding:0 0 20px 0;
        }


        .pagination\:container {
            width: fit-content;
            margin: 20px auto;
            display: flex;
            align-items: center;
        }

        .arrow\:text {
          display: block;
          vertical-align: middle;
          font-size: 13px;
          vertical-align: middle;
          color: white;
        }

        .pagination\:number {
             --size: 32px;
             --margin: 6px;
             margin: 0 var(--margin);
             border-radius: 6px;
             background-color: #d39e00;
              color: white;
              max-width: auto;
              min-width: var(--size);
              height: var(--size);
              display: flex;
              align-items: center;
              justify-content: center;
              cursor: pointer;
              padding: 0 6px;
              @media (hover: hover) {
                &:hover {
                  background-color: rgba(92, 95, 171,3%);
            }
          }
          &:active {
              background-color: rgba(92, 95, 171,3%);
          }
        }

        .pagination\:active {
          background: lighten(#202020, 3%);
          position: relative;
        }

        /* helper css*/

        .selected{
            border: 2px solid #d39e00;
            color:#d39e00;
            background:#fff;
        }
        header{
            height: 75px;
            background: grey;
        }
        .search-form{
            width: 50%;
            margin: 10px;
            display: inline-block;
        }

        table{
            margin: 60px auto 0px auto;
            border: 3px solid black;
        }
        td{

            border: 1px solid black;
        }
        .balance{
            float: right;
            margin: 10px;
            background-color: white;

            border: 1px solid transparent;
            border-radius: .25rem;

            display: inline-block;
            font-weight: 400;
            text-align: center;
            white-space: nowrap;
            vertical-align: middle;
            user-select: none;
    border: 1px solid transparent;
    padding: 10px 10px 0px 10px;
    line-height: 1.5;
    border-radius: .25rem;
    transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
    border-color: #ffc107;
        }
         .header_logo{

            padding: 5px;
            display: inline-block;
        }
        .header_logo-link > img{
            width: 65px;
            height: 65px;
            }
        .logout_m{
            float:right;
             margin:10px;
        }
        .tooltip {
  position: relative;
  display: inline-block;
}

.tooltip .tooltiptext {
  visibility: hidden;
  width: 140px;
  background-color: #555;
  color: #fff;
  text-align: center;
  border-radius: 6px;
  padding: 5px;
  position: absolute;
  z-index: 1;
  bottom: 150%;
  left: 50%;
  margin-left: -75px;
  opacity: 0;
  transition: opacity 0.3s;
}

.tooltip .tooltiptext::after {
  content: "";
  position: absolute;
  top: 100%;
  left: 50%;
  margin-left: -5px;
  border-width: 5px;
  border-style: solid;
  border-color: #555 transparent transparent transparent;
}

.tooltip:hover .tooltiptext {
  visibility: visible;
  opacity: 1;
}
    </style>
</head>
<body>
<header>

    <nav class="">
    {% if user.is_authenticated %}

        <div class="header_head">
            <div class="header_logo">
                <a href="{% url 'products:product-list' %}" class="header_logo-link">
                   <img src="{% static '/images/new.png'%}" alt="logo" class="header_logo-pic">
                </a>
             </div>

            <form method="POST" action="{% url 'account_logout' %}" class="logout_m" >
                {% csrf_token %}
                <input type="submit" value="logout" style="padding: 7px 7px 10px 7px;">
            </form>


            <a href="{% url 'accounts:my_profile' %}" class="btn btn-warning" style="float:right; margin:18px;background-color:white;">Your Purchases</a>






            <a href="{% url 'shopping_cart:order_summary' %}" class="btn btn-warning" style="float:right; margin:18px;background-color:white;">Go to Cart</a>

            <a href="https://t.me/amazonbelarus" class="btn btn-warning" style="float:right; margin:18px;background-color:white;">Top up balance</a>



  <a href="#!" class="btn btn-warning" style="float:right; margin:18px;background-color:white;">Balance: {{ request.user.profile.balance }}</a>


        </div>

	{% endif %}

    </nav>
</header>

    {% include 'messages.html' %}
    <div class="container">
        {% block content %}{% endblock content %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    {% block script %}{% endblock script %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.0.2/tablesort.min.js'></script>
<script src="https://kit.fontawesome.com/6be488ea4d.js" crossorigin="anonymous"></script>



<script>
  new Tablesort(document.getElementById('table-id'));
</script>

</body>
</html>

templates/messages.html
{% if messages %}

 	<style type="text/css">
 		div.messages{
 			background-color: #ff6b6b;
 			color: #f7fff7;
 		}
 		ul.messages{
 			list-style-type: none;
 		}
 	</style>

    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

templates/profile.html
{% extends 'base.html' %}

{% block content %}

<table id="table-id" class="table table-hover table-bordered text-center">
    <thead>
    <tr class="text-center">

        <th>Date ordered</th>
          <th>Country</th>
        <th>State</th>
        <th>City</th>
        <th>Track</th>
        <th>Check</th>

      </tr>
        </thead>
      {% for order in my_orders %}
        {% for item in order.items.all %}
        <tr>
          <td>{{ order.date_ordered }}</td>
          <td>{{ item.product.country }}</td>
          <td>{{ item.product.state }}</td>
          <td>{{ item.product.city }}</td>
          <td>{{ item.product.number_track }}
              <a href="{% url 'accounts:copy_item' item.id %}" data-balloon="remove this item from cart" class="text-danger" onclick="return confirm_copy();">
                <i class="fas fa-copy"></i>
              </a>
          </td>
          <td><a href="https://www.fedex.com/fedextrack/?trknbr={{ item.product.number_track }}" target="_blank" class="btn btn-warning" style="float:right; margin:18px;background-color:white;">Check</a></td>

        </tr>
        {% endfor %}
      {% empty %}
        <tr>
          <td colspan= 6> You have no orders.</td>
        </tr>
      {% endfor %}
        <thead>
      <tr>
        <td colspan=6>
          <a href="{% url 'products:product-list' %}" class="btn btn-warning pull-left">
            {% if not order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
          </a> 
        </td>
      </tr>
    </thead>
    </table>

{% endblock content %}