cart/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from .views import redirect_view


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profiles/', include('accounts.urls', namespace='accounts')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^cart/', include('shopping_cart.urls', namespace='shopping_cart')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'', redirect_view)
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url

from .views import product_list
from .views import search
from .views import downfile

app_name = 'products'

urlpatterns = [
    url(r'^$', product_list, name='product-list'),
    url(r'^search/$', search, name='search'),
    url(r'^downfile/$', downfile, name='downfile'),
]

shopping_cart/urls.py
from django.conf.urls import url


from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    success,
    balance
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^update-transaction/(?P<token>[-\w]+)/$', update_transaction_records,
        name='update_records'),
    url(r'^check_balance/$', balance, name='balance')
]

products/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Product(models.Model):
    country = models.CharField(max_length=50, verbose_name='Страна')
    state = models.CharField(max_length=50, verbose_name='Штат')
    city = models.CharField(max_length=50, verbose_name='Город')
    data = models.CharField(max_length=100, verbose_name='Дата')
    status = models.CharField(max_length=50, verbose_name='Статус')
    number_track = models.CharField(max_length=50, verbose_name='Номер трека')
    price = models.IntegerField()

    def __str__(self):
        return self.data


class News(models.Model):
    date = models.DateField(auto_now=False, verbose_name='Дата')
    title = models.CharField(max_length=50, verbose_name='Название')
    description = models.CharField(max_length=1000, verbose_name='Содержание')

products/views.py
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from shopping_cart.models import Order
from .models import Product, News
from django.db.models import Q
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
import xml.etree.ElementTree as ET
import csv
import io


@login_required
def product_list(request):
    object_list = Product.objects.all()
    filtered_orders = Order.objects.filter(owner=request.user.profile, is_ordered=False)
    current_order_products = []
    news_list = News.objects.filter().order_by('-date')[:3]
    paginator = Paginator(object_list, 50)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if filtered_orders.exists():
    	user_order = filtered_orders[0]
    	user_order_items = user_order.items.all()
    	current_order_products = [product.product for product in user_order_items]

    context = {
        'page_obj': page_obj,
        'object_list': object_list,
        'current_order_products': current_order_products,
        'news_list': news_list,
    }

    return render(request, "products/product_list.html", context)


@login_required
def search(request):
    country = request.POST['country']
    state = request.POST['state']
    city = request.POST['city']
    data = request.POST['data']
    result_list = Product.objects.filter(country__contains=country, state__contains=state, city__contains=city, data__contains=data)
    filtered_orders = Order.objects.filter(owner=request.user.profile, is_ordered=False)
    current_order_products = []
    if filtered_orders.exists():
        user_order = filtered_orders[0]
        user_order_items = user_order.items.all()
        current_order_products = [product.product for product in user_order_items]

    context = {
        'empty': 'Check the Spelling',
        'data': data,
        'country': country,
        'state': state,
        'city': city,
        'result_list': result_list,
        'current_order_products': current_order_products
    }

    return render(request, 'products/search.html', context)


@login_required
def downfile(request):
    if not request.user.is_staff:
        return HttpResponseRedirect('/products/')
    if request.method == 'POST':
        upload = request.FILES['file']
        data_set = upload.read().decode('UTF-8')
        io_string = io.StringIO(data_set)
        next(io_string)
        for column in csv.reader(io_string, delimiter=',', quotechar="|"):
            try:
                _, created = Product.objects.update_or_create(
                    country=column[0],
                    state=column[1],
                    city=column[2],
                    data=column[4],
                    status=column[5],
                    number_track=column[3],
                    price=column[6]
                )
            except Exception:
                continue

        # with open(os.path.abspath(upload.name), newline='') as f:
        #     reader = csv.reader(f)
        #     for row in reader:
        #         array = row.split(',')
        #         state = array[0].text
        #         city = array[1].text
        #         data = array[3].text
        #         status = array[4].text
        #         number_track = array[2].text
        #         price = array[5].text
        #         Product.objects.create(state=state, city=city, data=data, status=status, number_track=number_track, price=price)
        return HttpResponseRedirect('/admin/')
    else:
        context = {}
    return render(request, 'products/file.html', context)

products/templates/products/file.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'products:downfile' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="file">
    <input type="submit">
</form>
</body>
</html>

products/templates/products/product_list.html
{% extends 'base.html' %}

{% block content %}
    {{ message }}

<div class="list-group" style="padding:20px 28px 0 0;">
    {% for news in news_list %}
  <a href="#" class="list-group-item list-group-item-action flex-column align-items-start ">
    <div class="d-flex w-100 justify-content-between" >
      <h5 class="mb-1">{{news.title}}</h5>
      <small>{{news.date}}</small>
    </div>
    <p class="mb-1">{{news.description}}</p>
  </a>
    {% empty %}
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start active">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">Any news</h5>
    </div>
  </a>
    {% endfor %}
</div>
<div class="seaching_form" style="padding-top: 80px;">
    <form method="POST" action="{% url 'products:search' %}"  class="search-form" style="display:contents;">
        {% csrf_token %}
        <input name="country" type="text" class="search_input" placeholder="Search for Country...">


        <input name="state" type="text" class="search_input" placeholder="Search for State...">


        <input name="city" type="text" class="search_input" placeholder="Search for City...">
        <input name="data" type="text" class="search_input" placeholder="Search for Data...">
        <input type="submit" value="search">
    </form>
</div>
 <section style="padding:0 28px 0 0;">
        <div class="row" style="margin-left: 0px; width:100%;">
            <table  class="table table-hover table-bordered text-center">
                <thead>
                <tr class="text-center" style="font-weight: 700;">
                    <th>Country</th>
                    <th>State</th>
                    <th style="width:160px;">City</th>
                    <th style="width:220px;">Data</th>
                    <th>Status</th>
                    <th>Buy</th>
                </tr>
             </thead>
                    {% for object in page_obj.object_list %}

                    <tr>
                        <td>{{ object.country }}</td>
                        <td>{{ object.state }}</td>
                        <td>{{ object.city }}</td>
                        <td>{{ object.data }}</td>
                        <td>{{ object.status }}</td>
                        <td>
                            {% if object in user.profile.ebooks.all %}
                            <!-- add a button here to see the product -->
                            You own this
                            {% elif object in current_order_products %}
                            <a href="{% url 'shopping_cart:order_summary' %}" class="btn btn-warning">Go to Cart</a>
                            {% else %}
                            <a href="{% url 'shopping_cart:add_to_cart' object.id %}" class="btn btn-warning">Add to Cart</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}

            </table>
            {% if page_obj.paginator.num_pages > 1 %}
<div>
<div class="pagination:container">
{% if page_obj.has_previous %}
<a href="?page={{ page_obj.previous_page_number  }}">
  <div class="pagination:number arrow pressable">
    <svg width="18" height="18">
      <use xlink:href="#left" />
    </svg>
  </div>
</a>
{% endif %}

<a href="?page=1">
  <div class="pagination:number pressable {% if  page_obj.number == 1 %} selected {% endif %}">
    1
  </div>
</a>

<a href="?page=2">
  <div class="pagination:number pressable {% if  page_obj.number == 2 %} selected {% endif %}">
    2
  </div>
</a>

{% if page_obj.number != 1 and page_obj.number != 2 %}
<a href="?page={{ page_obj.number }}">
  <div class="pagination:number pressable selected">
    {{ page_obj.number }}
  </div>
</a>
{% endif %}

{% if page_obj.number != page_obj.paginator.num_pages and page_obj.paginator.num_pages > 2 %}
<a href="?page={{ page_obj.paginator.num_pages }}">
  <div class="pagination:number pressable">
    {{ page_obj.paginator.num_pages }}
  </div>
</a>
{% endif %}


{% if page_obj.has_next  %}
<a href="?page={{ page_obj.next_page_number   }}">
  <div class="pagination:number arrow pressable">
    <svg width="18" height="18">
      <use xlink:href="#right" />
    </svg>
  </div>
</a>
{% endif %}
</div>

<svg class="hide">
  <symbol id="left" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path></symbol>
  <symbol id="right" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path></symbol>
</svg>
</div>
{% endif%}
</div>
 </section>



{% endblock content %}

products/templates/products/search.html
{% extends 'base.html' %}

{% block content %}
    {{ message }}
 <section>
        <div class="row">
            <table class="table table-hover table-bordered text-center">
                <tr class="text-center" style="font-weight: 700;">
                    <td>Country</td>
                    <td>State</td>
                    <td>City</td>
                    <td>Data</td>
                    <td>Status</td>
                    <td>Buy</td>
                </tr>

                    {% for elem in result_list %}
                    <tr>
                        <td>{{ elem.country }}</td>
                        <td>{{ elem.state }}</td>
                        <td>{{ elem.city }}</td>
                        <td>{{ elem.data }}</td>
                        <td>{{ elem.status }}</td>
                        <td>
                            {% if elem in user.profile.ebooks.all %}
                            <!-- add a button here to see the product -->
                            You own this
                            {% elif elem in current_order_products %}
                            <a href="{% url 'shopping_cart:order_summary' %}" class="btn btn-warning">Go to Cart</a>
                            {% else %}
                            <a href="{% url 'shopping_cart:add_to_cart' elem.id %}" class="btn btn-warning">Add to Cart</a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
            </table>
            {% if empty %}
            <h1 style="margin-left: 400px;">{{empty}}</h1>
        </div>
    </div>
    {% endif %}
</div>
 </section>

{% endblock content %}